# Generated by Django 3.0.8 on 2020-07-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
